=== abhi1988srivastava/Ruby/stud_xsd.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="file:///C:/stud"
elementFormDefault="qualified">

<xs:element name="class">

<xs:complexType>
  <xs:sequence>
    <xs:element name="student">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="id" type="xs:integer"/>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="marks" type="xs:integer"/>
		</xs:sequence>
	</xs:complexType>
  </xs:sequence>
</xs:complexType>

</xs:element>

=== abhi1988srivastava/Ruby/stud.xml
<?xml version="1.0" encoding="UTF-8"?>

<class xmlns="file:///C:/stud"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="file:///C:/stud/stud_xsd.xsd">

	<student>
		<id>1</id>
		<name>Abhinav</name>
		<marks>123</marks>
	</student>
	<student>
		<id>2</id>
		<name>Adi</name>
		<marks>567</marks>
	</student>
	
</class>
